testcases = [
    'book-flight',
    'choose-date',
    'choose-date-easy',
    'choose-date-medium',
    'choose-list',
    'click-button',
    'click-button-sequence',
    'click-checkboxes',
    'click-checkboxes-large',
    'click-checkboxes-soft',
    'click-checkboxes-transfer',
    'click-collapsible',
    'click-collapsible-2',
    'click-color',
    'click-dialog',
    'click-dialog-2',
    'click-link',
    'click-menu',
    'click-option',
    'click-pie',
    'click-scroll-list',
    'click-shades',
    'click-shape',
    'click-tab',
    'click-tab-2',
    'click-tab-2-hard',
    'click-test',
    'click-test-2',
    'click-widget',
    'count-shape',
    'email-inbox',
    'email-inbox-forward-nl',
    'email-inbox-forward-nl-turk',
    'email-inbox-nl-turk',
    'enter-date',
    'enter-password',
    'enter-text',
    'enter-text-dynamic',
    'enter-time',
    'focus-text',
    'focus-text-2',
    'grid-coordinate',
    'guess-number',
    'identify-shape',
    'login-user',
    'login-user-popup',
    'multi-layouts',
    'multi-orderings',
    'navigate-tree',
    'search-engine',
    'social-media',
    'social-media-all',
    'social-media-some',
    'tic-tac-toe',
    'use-autocomplete',
    'use-spinner',
]

mwpp_attrs = {
    'basic': [
        'id',
        'classes',
        'value',
    ],
    'position': [
        'left',
        'top',
        'width',
        'height',
    ],
    'color': {
        'bgColor': 'background-color',
        'fgColor': 'color',
    }
}

not_clickable_tag = [
    'body',
    'div',
    'form', 
    'h1', 
    'h2', 
    'h3', 
    'h4',
    'h5', 
    'h6',  
    't', 
    'tr', 
    'td', 
    'th', 
    'p',
    'li',
]

miniwob_attrs = [
    'id',
    'type',
    'classes',
    'value',
    'rgba',
    'size',
]

special_classes = [
    'alink', 
    'color', 
    'share', 
    'copy', 
    'embed', 
    'menu-user', 
    'block-user', 
    'report', 
    'email-forward', 
    'forward-sender', 
    'email-reply', 
    'email-sender'
]